name: Deploy to Vercel Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope schoolhouselane --yes
        env:
          VERCEL_ORG_ID: team_srG9V9DtyHjhyrEQwqCvEcve
          VERCEL_PROJECT_ID: prj_rzwaNxVEqvDYnVZ6Lxs3cy7DaCrV
